
//Getters
export const GET_RECEIVE_DEFAULT_INFO = 'common/GET_RECEIVE_DEFAULT_INFO'
export const GET_RECEIVE_INPUT_SELECTOR_DATA = 'inputSelector/GET_RECEIVE_INPUT_SELECTOR_DATA'

// Actions
export const ACTION_RECEIVE_DEFAULT_INFO = 'common/ACTION_RECEIVE_DEFAULT_INFO'
            // appInputSelector
export const ACTION_RECEIVE_INPUT_SELECTOR_DATA = 'appInputSelector/ACTION_RECEIVE_INPUT_SELECTOR_DATA'
export const ACTION_SEND_INPUT_SELECTOR_SELECTED_DATA = 'appInputSelector/ACTION_SEND_INPUT_SELECTOR_SELECTED_DATA'
export const ACTION_STORE_INPUT_SELECTOR_SELECTED_DATA = 'appInputSelector/ACTION_STORE_INPUT_SELECTOR_SELECTED_DATA'


            // appSelector
export const ACTION_GET_APP_SELECTOR_DEFAULT_DATA = 'appSelector/ACTION_GET_APP_SELECTOR_DEFAULT_DATA'
export const ACTION_SET_APP_SELECTOR_DATA = 'appSelector/ACTION_SET_APP_SELECTOR_DATA'

            // appDataSelector
export const ACTION_SET_APP_DATA_SELECTOR = 'appDataSelector/ACTION_SET_APP_DATA_SELECTOR'

            // appTableServerSide
export const ACTION_RECEIVE_TABLE_DATA = 'appTableServerSide/ACTION_RECEIVE_TABLE_DATA'
export const ACTION_RECEIVE_SORTED_TABLE_DATA = 'appTableServerSide/ACTION_RECEIVE_SORTED_TABLE_DATA'



// Mutations
export const MUTATE_RECEIVE_DEFAULT_INFO = 'common/MUTATE_RECEIVE_DEFAULT_INFO'

            // appInputSelector
export const MUTATE_RECEIVE_INPUT_SELECTOR_DATA = 'appInputSelector/ACTION_RECEIVE_INPUT_SELECTOR_DATA'
export const MUTATE_STORE_INPUT_SELECTOR_SELECTED_DATA = 'appInputSelector/MUTATE_STORE_INPUT_SELECTOR_SELECTED_DATA'


            // appDataSelector
export const MUTATE_SET_APP_DATA_SELECTOR = 'appDataSelector/MUTATE_SET_APP_DATA_SELECTOR'

            // appSelector
export const MUTATE_GET_APP_SELECTOR_DEFAULT_DATA = 'appSelector/MUTATE_GET_APP_SELECTOR_DEFAULT_DATA'
export const MUTATE_SET_APP_SELECTOR_DATA = 'appSelector/MUTATE_SET_APP_SELECTOR_DATA'

            // appTableServerSide
export const MUTATE_RECEIVE_TABLE_DATA = 'appTableServerSide/MUTATE_RECEIVE_TABLE_DATA'
export const MUTATE_RECEIVE_SORTED_TABLE_DATA = 'appTableServerSide/MUTATE_RECEIVE_SORTED_TABLE_DATA'